import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {AnalogView} from '../../app/analog/view.js';
const html=readFileSync(new URL('../../index.html',import.meta.url),'utf8');
const css=readFileSync(new URL('../../app/app.css',import.meta.url),'utf8');
assert.match(html,/<nav class="seg docktabs an-tabs" id="an-dock-tabs" role="tablist"/,'ADC and DAC use the shared dock-tab style');
assert.match(html,/id="an-panel-adc"[^>]*role="tabpanel"[^>]*tabindex="0"/,'ADC tab panel is keyboard-focusable');
assert.match(html,/id="an-panel-dac"[^>]*role="tabpanel"[^>]*tabindex="0"/,'DAC tab panel is keyboard-focusable');
assert.doesNotMatch(css,/#tab-analog \.an-tabs button\s*\{/,'ADC/DAC tabs inherit the same font and spacing as other dock tabs');
const ids=[...html.matchAll(/\bid="(an-[^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'ADC/DAC controls must have distinct IDs');
const elements=new Map(ids.map(id=>[id,{value:'',style:{},options:[],handlers:{},addEventListener(event,fn){this.handlers[event]=fn;},width:1000,height:260}]));
for(const [,attrs,id] of html.matchAll(/<input\b([^>]*\bid="(an-[^"]+)"[^>]*)>/g))elements.get(id).value=attrs.match(/\bvalue="([^"]*)"/)?.[1]??'';
for(const [,id,body] of html.matchAll(/<select\b[^>]*\bid="(an-[^"]+)"[^>]*>([\s\S]*?)<\/select>/g)){
  const options=[...body.matchAll(/<option\b([^>]*)>([^<]*)<\/option>/g)].map(([,a,t])=>({value:a.match(/\bvalue="([^"]*)"/)?.[1]??t,selected:a.includes('selected')}));
  elements.get(id).options=options;elements.get(id).value=(options.find(o=>o.selected)??options[0])?.value??'';
}
elements.get('an-wave').value='sine';
let trace=false,coordinates=[];
const context={fillRect(){},clearRect(){},beginPath(){},stroke(){},setLineDash(){},fillText(){},moveTo(x,y){if(trace)coordinates.push([x,y]);},lineTo(x,y){if(trace)coordinates.push([x,y]);},set strokeStyle(v){trace=v==='#ffd15c';}};
for(const id of ['an-adc-canvas','an-dac-canvas'])elements.get(id).getContext=()=>context;
const makeClassList=()=>({values:new Set(),toggle(name,on){on?this.values.add(name):this.values.delete(name);}});
const tabs=['adc','dac'].map(name=>({dataset:{anTab:name},classList:makeClassList(),attrs:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(event,fn){this.handlers??={};this.handlers[event]=fn;},focus(){}}));
const panels=['adc','dac'].map(name=>({dataset:{anPage:name},classList:makeClassList(),hidden:false}));
globalThis.document={getElementById(id){assert.ok(elements.has(id),`missing ${id}`);return elements.get(id);},querySelectorAll(selector){return selector==='#an-dock-tabs [data-an-tab]'?tabs:selector==='#tab-analog [data-an-page]'?panels:[];}};
const view=new AnalogView();view.init();assert.equal(view.wave.length,100,'preview is the same complete-cycle LUT as output');
assert.equal(view.page,'adc');assert.equal(tabs[0].attrs['aria-selected'],'true');assert.equal(panels[1].hidden,true);
tabs[0].handlers.keydown({key:'ArrowRight',preventDefault(){}});assert.equal(view.page,'dac');assert.equal(tabs[1].attrs['aria-selected'],'true');assert.equal(panels[0].hidden,true);
tabs[1].handlers.keydown({key:'Home',preventDefault(){}});assert.equal(view.page,'adc');assert.equal(panels[0].hidden,false);
assert.ok(elements.get('an-dac-start').disabled);
elements.get('an-max').value='3';elements.get('an-min').value='1';elements.get('an-max').handlers.change();
assert.equal(elements.get('an-amplitude').value,'1');assert.equal(elements.get('an-dac-offset').value,'2');
assert.equal(elements.get('an-vpp').value,'2');assert.ok(view.wave.length);
elements.get('an-vpp').value='1';elements.get('an-vpp').handlers.change();
assert.equal(elements.get('an-min').value,'1.5');assert.equal(elements.get('an-max').value,'2.5');
elements.get('an-wave').value='dc';elements.get('an-wave').handlers.change();
assert.ok(elements.get('an-amplitude').disabled);assert.ok(view.wave.every(r=>r.volts===2));
assert.equal(elements.get('an-min').value,'2');assert.equal(elements.get('an-max').value,'2');
elements.get('an-wave').value='sine';elements.get('an-wave').handlers.change();assert.equal(elements.get('an-vpp').value,'1');
elements.get('an-max').value='5';elements.get('an-max').handlers.change();
assert.equal(view.wave.length,0);assert.match(elements.get('an-wave-state').textContent,/不自动削顶/);
elements.get('an-max').value='2.5';elements.get('an-max').handlers.change();assert.equal(view.wave.length,100);
view.store.append({codes:Uint16Array.from({length:10},()=>30000),rate:1000,bits:16});view.total=10;
elements.get('an-time').value='.01';view.renderAdc();
assert.ok(coordinates.length);assert.equal(Math.max(...coordinates.map(p=>p[0])),90,'10 samples at 1kSa/s span 9ms, not an entire 100ms screen');
assert.match(elements.get('an-stats').textContent,/当前时窗超过记录长度/);
coordinates=[];elements.get('an-freeze').checked=true;view.renderAdc();assert.equal(coordinates.length,0);
console.log('Analog page: HTML binding, ADC/DAC tab keyboard/accessibility, linked generator levels, coherent LUT, DC controls, clipping rejection, ADC partial-record time axis/freeze PASS');
