import assert from 'node:assert/strict';
import { DebugSession } from '../../app/dbg/session.js';
import { watchSpec, DWT, dwtReg } from '../../app/dbg/dwt.js';
import { runCmd } from '../../app/dbg/cmd.js';
const s=new DebugSession(); await s.connect({mock:true});
assert.throws(()=>watchSpec(0x20000001,4)); assert.throws(()=>watchSpec(0,3));
assert.throws(()=>watchSpec(0,4,'x')); assert.throws(()=>watchSpec(-1));
s.probe.ppb.set(DWT.DEMCR,0x123);
s.probe.ppb.set(DWT.FUNCTION,4); // another trace client owns slot0
await runCmd('wp 0x20000000 w 4',s);
assert.equal(s.dwt.items[0].slot,1);
assert.equal(s.probe.ppb.get(DWT.DEMCR),0x01000123);
await runCmd('wp 0x20000000 w 4',s); assert.equal(s.dwt.items.length,1);
await s.memRead(0x20000000,4); assert.equal(s.probe.dfsr&4,0);
assert.equal(s.probe._cpuAccess(0x20000000,4,'r'),false);
assert.equal(s.probe._cpuAccess(0x20000003,1,'w'),true);
assert.match(await s.dwt.haltReason(),/#2/);
await runCmd('wp 0x20000008 r 8',s); await runCmd('wp 0x20000010 rw 4',s);
await assert.rejects(()=>runCmd('wp 0x20000020 w 4',s),/已用完/);
assert.equal(s.probe._cpuAccess(0x2000000f,1,'r'),true);
assert.match((await runCmd('wpl',s)).lines.at(-1).t,/3 个观察点/);
await runCmd('wpd #2',s); assert.equal(s.probe.ppb.get(dwtReg(DWT.FUNCTION,1)),0);
await s.resetHalt(); assert.equal(s.probe.ppb.get(dwtReg(DWT.FUNCTION,2))&15,5);
await s.disconnect(); assert.equal(s.dwt.items.length,0);
const unsupported=new DebugSession(); await unsupported.connect({mock:true});
unsupported.arch={name:'riscv'}; await assert.rejects(()=>runCmd('wp 0x20000000',unsupported),/Cortex-M/);
unsupported.arch={name:'arm'}; unsupported.probe.ppb.set(DWT.CPUID,0x410fd213);
await assert.rejects(()=>unsupported.dwt.add(0x20000000),/M3\/M4\/M7/);
await unsupported.disconnect();
const bad=new DebugSession(); await bad.connect({mock:true});
const orig=bad.probe._readWord.bind(bad.probe);
bad.probe._readWord=async a=>a===DWT.MASK?0:orig(a);
await assert.rejects(()=>bad.dwt.add(0x20000000,4),/范围/);
assert.equal(bad.dwt.items.length,0); assert.equal(bad.probe.ppb.get(DWT.FUNCTION),0);
await bad.disconnect();
console.log('dbg-dwt: modes/alignment/capacity, ownership, readback rollback, reset, disconnect, architecture guards PASS');
